version: 1
formatters:
  default:
    format: "%(asctime)s %(levelname)-8s [%(threadName)s %(filename)s:%(lineno)d]: %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: INFO
    formatter: default

  rotating_file_handler:
    class: logging.handlers.RotatingFileHandler
    level: INFO
    filename: emotional_speech.log
    maxBytes: 10000000 # 10MB
    backupCount: 10
    formatter: default

loggers:
  emotional_speech:
    handlers: [console, rotating_file_handler]
    level: INFO
    propagate: false
