env:
  browser: true
  es2020: true
extends:
  - 'eslint:recommended'
  - 'prettier'
  - 'prettier/react'
  - 'plugin:react/recommended'
parserOptions:
  ecmaFeatures:
    jsx: true
  ecmaVersion: 11
  sourceType: module
plugins:
  - react
rules:
  quotes: [error, single]
  indent: [error, 2]
  semi: [error, never]
  no-trailing-spaces: [error, 0]
  max-len: 
    - error
    - code: 30
  